name: alpine ci

on:
  workflow_dispatch:
  push:
    branches: master
    paths: 'alpine/**'
  # monthly update
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: efaille/actions/docker-base-image-ci@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          context: alpine
          tag: efaille/alpine:latest
  trigger-java-ci-workflow:
    uses: efaille/dockerfiles/.github/workflows/java.yml@master
