name: alpine ci

on:
  workflow_dispatch:
  push:
    branches: master
    paths: 'alpine/**'
  # monthly update
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: efaille/actions/docker-base-image-ci@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          context: alpine
          tag: efaille/alpine:latest
  java-ci:
    needs: build
    uses: efaille/dockerfiles/.github/workflows/java.yml@master
    secrets: inherit
  node-ci:
    needs: build
    uses: efaille/dockerfiles/.github/workflows/node.yml@master
    secrets: inherit
  golang-ci:
    needs: build
    uses: efaille/dockerfiles/.github/workflows/golang.yml@master
    secrets: inherit
  nginx-ci:
    needs: build
    uses: efaille/dockerfiles/.github/workflows/nginx.yml@master
    secrets: inherit
  mysql-ci:
    needs: build
    uses: efaille/dockerfiles/.github/workflows/mysql.yml@master
    secrets: inherit
  supervisor-alpine-ci:
    needs: build
    uses: efaille/dockerfiles/.github/workflows/supervisor-alpine.yml@master
    secrets: inherit
