name: java ci

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: master
    paths: 'java/**'
  # monthly update
  #schedule:
  #  - cron: 0 0 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: efaille/actions/docker-base-image-ci@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          context: java
          tag: efaille/java:latest
