name: maven ci

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: master
    paths: 'maven/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: efaille/actions/docker-base-image-ci@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: maven
          tag: efaille/maven:latest
