name: nginx-proxy ci

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: master
    paths: 'nginx-proxy/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: efaille/actions/docker-image-ci@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: nginx-proxy
          tag: efaille/nginx-proxy:latest
