name: nginx-php-alpine ci

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: master
    paths: 'nginx-php-alpine/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: efaille/actions/docker-image-ci@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: nginx-php-alpine
          tag: efaille/nginx-php-alpine:latest
