name: node ci

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: master
    paths: 'node/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: efaille/actions/docker-base-image-ci@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          context: node
          tag: efaille/node:latest
