name: ci

on:
  push:
    branches: master
    paths: 'alpine/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          path: alpine 
          repository: efaille/alpine
          tag_with_ref: true
