name: ubuntu ci

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: master
    paths: 'ubuntu/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: efaille/actions/docker-image-ci@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: ubuntu
          tag: efaille/ubuntu:latest
