name: wordpress-alpine ci

on:
  workflow_dispatch:
  push:
    branches: master
    paths: 'wordpress-alpine/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          path: wordpress-alpine
          repository: efaille/wordpress-alpine
          tag_with_ref: true
